name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby: ['2.7', '3.0', '3.2']
        appraisal: ['rails-7.2', 'rails-8-sprockets', 'rails-8-propshaft']
        exclude:
          - ruby: '2.7'  # Rails 8 requires Ruby 3.2+
            appraisal: 'rails-8-sprockets'
          - ruby: '2.7'
            appraisal: 'rails-8-propshaft'
          - ruby: '3.0'
            appraisal: 'rails-8-sprockets'
          - ruby: '3.0'
            appraisal: 'rails-8-propshaft'
    steps:
      - uses: actions/checkout@v2
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
      - name: Install dependencies
        run: |
          gem install bundler
          bundle install
      - name: Install appraisals
        run: bundle exec appraisal install
      - name: Run tests
        run: bundle exec appraisal ${{ matrix.appraisal }} rails test --verbose